FROM nginx

RUN apt-get update
RUN apt-get install -y zip jq dos2unix

COPY pixelmon /tmp/resource-pack/pixelmon
COPY common /tmp/resource-pack/common
COPY merge.sh /tmp/resource-pack/merge.sh

WORKDIR /tmp/resource-pack
RUN dos2unix merge.sh
RUN bash merge.sh pixelmon

COPY version.txt /tmp/resource-pack/merged/version.txt

RUN mkdir -p /usr/share/nginx/html/
RUN cd /tmp/resource-pack/merged && \
    zip -r resource-pack.zip . && \
    mv resource-pack.zip /usr/share/nginx/html/resource-pack.zip

RUN rm -rf /tmp/resource-pack
